allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
minimumReleaseAgeExclude:
  - eslint@10.10.0 || 10.12.0
  - prettier@3.9.9
  - sass@1.105.0
patchedDependencies:
  opentype.js: patches/opentype.js.patch
